---
- name: Install Clickhouse
  hosts: clickhouse
  vars_files:
    - vars.yml
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
            dest: "/tmp/{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib (rescue mode)
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "/tmp/clickhouse-common-static-{{ clickhouse_version }}.rpm"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - /tmp/clickhouse-common-static-{{ clickhouse_version }}.rpm
          - /tmp/clickhouse-client-{{ clickhouse_version }}.rpm
          - /tmp/clickhouse-server-{{ clickhouse_version }}.rpm
        disable_gpg_check: true
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      become: true
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  handlers:
    - name: Start vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Download vector packages
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
        dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
    - name: Install vector packages
      become: true
      ansible.builtin.yum:
        name: "./vector-{{ vector_version }}-1.x86_64.rpm"
        disable_gpg_check: true
    - name: Apply vector template
      become: true
      ansible.builtin.template:
        src: vector.yml.j2
        dest: "{{ vector_config_dir }}/vector.yml"
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        validate: vector validate --no-environment --config-yaml %s
    - name: Change vector systemd unit
      become: true
      ansible.builtin.template:
        src: vector.service.j2
        dest: /usr/lib/systemd/system/vector.service
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        backup: true
      notify: Start vector service

- name: Install Lighthouse
  hosts: lighthouse
  vars:
    nodejs_version: "16.x"  # Версия Node.js LTS
  tasks:
    - name: Install dependencies
      become: true
      ansible.builtin.yum:
        name: 
          - gcc-c++
          - make
          - curl
        state: present

    - name: Install Node.js
      become: true
      ansible.builtin.shell: |
        curl -sL https://rpm.nodesource.com/setup_{{ nodejs_version }} | bash -
      args:
        warn: false

    - name: Install Node.js package
      become: true
      ansible.builtin.yum:
        name: nodejs
        state: present

    - name: Install Lighthouse via npm
      become: true
      ansible.builtin.npm:
        name: lighthouse
        global: yes

    - name: Create Lighthouse directory
      become: true
      ansible.builtin.file:
        path: /etc/lighthouse
        state: directory
        mode: '0755'

    - name: Copy Lighthouse configuration
      become: true
      ansible.builtin.template:
        src: lighthouse-config.json.j2
        dest: /etc/lighthouse/config.json
        mode: '0644'

  handlers:
    - name: Restart Lighthouse (if necessary)
      become: true
      ansible.builtin.service:
        name: lighthouse
        state: restarted